version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    # volumes:
    #   - .zookeeper/data:/var/lib/zookeeper/data
    #   - .zookeeper/logs:/var/lib/zookeeper/logs
    networks:
      - debezium
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.1
    restart: always
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=100
    depends_on:
      - zookeeper
    # volumes:
    #   - .kafka/data:/var/lib/kafka/data
    networks:
      - debezium
  debezium-connect:
    container_name: debezium_connect
    image: debezium-connect-postgres
    restart: always
    build:
      context: debezium-connect
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    depends_on:
      - kafka
    # volumes:
    #   - .debezium_connect/data:/kafka/data
    #   - .debezium_connect/logs:/kafka/logs
    networks:
      - debezium
  debezium-ui:
    container_name: debezium_ui
    image: quay.io/debezium/debezium-ui:1.9
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect:8083
    depends_on:
      - debezium-connect
    networks:
      - debezium
  kafka-ui:
    container_name: kafka_ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9100:8080
    depends_on:
      - zookeeper
      - kafka
      - debezium-connect
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium_connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-connect:8083
    networks:
      - debezium
  transfer-golang:
    container_name: transfer-golang
    build: 
      context: ./transfer-golang
    restart: always
    environment:
      - ENV_NAME=dev
      - KAFKA_HOST=kafka
    depends_on:
      - zookeeper
      - kafka
      - debezium-connect
    networks:
      - debezium
networks:
  debezium:
    name: debezium
